### ISSUE TITLE
I think the "reference field" should  be camelCase by default.

### ISSUE THREAD

**Issue by thearabbit** [jeanfredrik/meteor-denormalize#3]
I think the "reference field" should  be camelCase by default.

``` js
Comments.cacheDoc('post', Post, ['title']); // reference filed = postId
```

**Comment by jeanfredrik** [comment]
Yeah, maybe that's the most common way to name reference fields/foreign keys in Meteor. It's hard to make something that works for everyone though, so I suggest you use the `referenceField` option either way.

**Comment by thearabbit** [comment]
Oh, I need to rewrite for all.

**Comment by thearabbit** [comment]
You could use `underscore string` package to do this.

**Comment by jeanfredrik** [comment]
The problem is that only one naming convention can be the default one. Right now it's `post_id` instead of `postId`. If I change the default now, the package won't be backwards compatible. Maybe it's best to provide a global option that changes the default naming? Example:

``` js
Denormalize.defaults.referenceField = function(name) {
    return name+'_id';
}
```

**Comment by thearabbit** [comment]
Sorry, I think that the `camelCase` it is still good.
