### ISSUE TITLE
Problem with updated primary fields, don't updated all of reference fields (only the first field)??

### ISSUE THREAD

**Issue by thearabbit** [jeanfredrik/meteor-denormalize#7]
I found the problem with multiple of reference fields.
When I updated the primary fields, It don't updated all of reference fields that related (only firth fields).

**Comment by jeanfredrik** [comment]
Can you give me an example?

**Comment by thearabbit** [comment]
When I insert many comments on `post_id: 1`, and then I update the `post_id: 1` it update the comments too but only the first record (not all that related to `post_id: 1`).
I thinks that you missing `multiple: true` for update.

**Comment by jeanfredrik** [comment]
Ah, that was it! I always seem to forget `multi` :)

I will publish a new version shortly

**Comment by thearabbit** [comment]
Wait, because I use this in my projects.

**Comment by jeanfredrik** [comment]
If you want to use an earlier version specify it in your `.meteor/packages` file. Like this:

```
jeanfredrik:denormalize@=0.7.0
```
